stages:
    - source
    - build
    - test
    - deploy

portable-source:
    stage: source
    tags:
        - linux
    image: "graphviz/graphviz:ubuntu-18.04"
    script:
        - ./autogen.sh
        - make dist
    artifacts:
        when: on_success
        expire_in: 1 week
        paths:
            - VERSION
            - COLLECTION
            - graphviz-*.tar.gz
    except:
        - tags

.build_template: &rpm_build_definition
    stage: build
    script:
        - ci/build.sh
    artifacts:
        when: on_success
        expire_in: 1 week
        paths:
            - Packages/*/*/*/*/*/*.rpm
            - Packages/*/*/*/*/*.rpm
    except:
        - tags

.build_template: &deb_build_definition
    stage: build
    script:
        - ci/build.sh
    artifacts:
        when: on_success
        expire_in: 1 week
        paths:
            - Packages/*/*/*/*/*/*deb
            - Packages/*/*/*/*/*.gz
    except:
        - tags

.test_template: &deb_test_definition
    stage: test
    script:
        - cat /etc/os-release
        - GV_VERSION=$( cat VERSION )
        - COLLECTION=$( cat COLLECTION )
        - zcat graphviz-${GV_VERSION}.tar.gz | tar xf -
        - . /etc/os-release
        - DIR=Packages/${COLLECTION}/${ID}/${VERSION_ID}
        - ARCH=$( uname -m )
        - apt install ./${DIR}/os/${ARCH}/libgraphviz4_${GV_VERSION}-1_amd64.deb
        - apt install ./${DIR}/os/${ARCH}/graphviz_${GV_VERSION}-1_amd64.deb
        - cd graphviz-${GV_VERSION}
        - ./configure
        - make -C tests/regression_tests/shapes check

centos6-build:
    <<: *rpm_build_definition
    tags:
        - linux
    image: "graphviz/graphviz:centos6"

centos7-build:
    <<: *rpm_build_definition
    tags:
        - linux
    image: "graphviz/graphviz:centos7"

centos8-build:
    <<: *rpm_build_definition
    tags:
        - linux
    image: "graphviz/graphviz:centos8"

          #fedora27-build:
          #<<: *rpm_build_definition
          #tags:
          #- graphviz,fedora27

          #fedora28-build:
          #<<: *rpm_build_definition
          #tags:
          #- graphviz,fedora28

fedora29-build:
    <<: *rpm_build_definition
    tags:
        - linux
    image: "graphviz/graphviz:fedora29"

fedora30-build:
    <<: *rpm_build_definition
    tags:
        - linux
    image: "graphviz/graphviz:fedora30"

fedora31-build:
    <<: *rpm_build_definition
    tags:
        - linux
    image: "graphviz/graphviz:fedora31"

fedora32-build:
    <<: *rpm_build_definition
    tags:
        - linux
    image: "graphviz/graphviz:fedora32"

fedora33-build:
    <<: *rpm_build_definition
    tags:
        - linux
    image: "graphviz/graphviz:fedora33"

ubuntu18-04-build:
    <<: *deb_build_definition
    tags:
        - linux
    image: "graphviz/graphviz:ubuntu-18.04"

        # FIXME: Ubuntu 18.10 is End of Life. Docker image cannot be created. Fix or remove
        #ubuntu18-10-build:
        #<<: *deb_build_definition
        #tags:
        #- graphviz,ubuntu18-10
        #only:
        #- master@graphviz/graphviz

ubuntu19-04-build:
    <<: *deb_build_definition
    tags:
        - linux
    image: "graphviz/graphviz:ubuntu-19.04"

ubuntu19-10-build:
    <<: *deb_build_definition
    tags:
        - linux
    image: "graphviz/graphviz:ubuntu-19.10"

ubuntu18-04-test:
    <<: *deb_test_definition
    tags:
        - linux
    image: "graphviz/graphviz:ubuntu-18.04"

ubuntu19-04-test:
    <<: *deb_test_definition
    tags:
        - linux
    image: "graphviz/graphviz:ubuntu-19.04"

ubuntu19-10-test:
    <<: *deb_test_definition
    tags:
        - linux
    image: "graphviz/graphviz:ubuntu-19.10"

deployment:
    stage: deploy
    script:
        - GV_VERSION=$( cat VERSION )
        - COLLECTION=$( cat COLLECTION )
        - eval $(ssh-agent -s)
        - cat "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - ssh-keyscan "$DEPLOY_HOST" >> ~/.ssh/known_hosts
        - chmod 644 ~/.ssh/known_hosts
        - chmod -R o-rwx Packages
        - chmod -R g-wx Packages
        - chmod -R g+X Packages
        - ssh "$DEPLOY_USER"@"$DEPLOY_HOST" 'rm -rf Packages/'"$COLLECTION"'/{fedora,centos,ubuntu}'
        - scp -r Packages/* "$DEPLOY_USER"@"$DEPLOY_HOST"':'Packages/
        - ssh "$DEPLOY_USER"@"$DEPLOY_HOST" 'for i in Packages/'"$COLLECTION"'/{fedora,centos}/*/{source,os/*,debug/*}; do createrepo $i; done'
        - scp graphviz-fedora.repo graphviz-centos.repo "$DEPLOY_USER"@"$DEPLOY_HOST"':'Packages/
        - ssh "$DEPLOY_USER"@"$DEPLOY_HOST" mkdir -p Packages/"$COLLECTION"/portable_source
        - md5sum graphviz-"$GV_VERSION".tar.gz >graphviz-"$GV_VERSION".tar.gz.md5
        - scp graphviz-"$GV_VERSION".tar.gz graphviz-"$GV_VERSION".tar.gz.md5 "$DEPLOY_USER"@"$DEPLOY_HOST"':'Packages/"$COLLECTION"/portable_source/
    only:
        - master@graphviz/graphviz
    tags:
        - graphviz,deploy
